
services:
  mockoon-multi:
    image: dockerhub.hayotbank.uz/mockoon-multi:1.2.1
    build: .
    container_name: mockoon-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./envs:/app/envs
    restart: unless-stopped
# docker buildx build --platform linux/amd64,linux/arm64 -t dockerhub.hayotbank.uz/mockoon-multi:1.2.0 --push .